### ISSUE TITLE
Bug: "ERROR: LoadError: InexactError: trunc(Int32, 2.172351299e9)"

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#11]
I saw this bug this morning and it is now solved in `0.3.18`.

This bug is when PySR tries to calculate the age of an equation. It seems that the offset I am using for "birthdate" of an equation, equal to `1e3*(time() - 1.6e9)`, and put into an Integer variable (so there is millisecond precision between equations), has actually now maxed out 32-bit integers. I have changed the precision to 64-bit and this issue is fixed.

I'm sorry for this bug; please update your binaries when you use PySR next.

**Comment by anicola** [comment]
Haha awesome! Thanks a lot @MilesCranmer! I was just trying to figure out where this came from :-)
