### ISSUE TITLE
[Feature] Refactor PySRRegressor to better support the scikit-learn interface

### ISSUE THREAD

**Issue by tttc3** [MilesCranmer/PySR#143]
The current implementation of PySRRegressor loosely supports interfacing with scikit-learn. However, when trying to use PySRRegressor with scikit-learn functions such as `cross_val_score(PySRRegressor(), X, y)` it currently does not work. 
I think poviding full compatibility with scikit-learn would, for me at least, be very useful. 

The easiest way to provide this additional compatibility would be refactoring the `PySRRegressor` to better conform with the [scikit-learn estimator development docs](https://scikit-learn.org/stable/developers/develop.html). 

To do this the following should be done:
1. No input validation in `__init__()`, instead validation should be performed in `.fit()`.
2. No kwargs in `__init__()`.
3. Move `__init__()` parameters that are not model hyper-parameters into `.fit()` or `.predict()`, e.g `tempdir` and `julia_project` are parameters that influence the execution of the model but not the model's result/score and thus should not be specified in `__init__()`.
4.  By doing the above, the custom `set_params()` and `get_params()` methods in `PySRRegressor` can be removed, allowing the inherited `BaseEstimator` to provide these methods. This will make interfacing with scikit-learn functions such as `cross_val_score`  much simpler.
5. Remove the `score` method in `PySRRegressor` that is currently `NotImplemented`. The `RegressorMixin` that `PySRRegressor` inherits provides a default scoring function that calculates an R^2 score.
6. Estimated attributes such as `PySRRegrssor().equations` should have trailing underscores e.g `PySRRegrssor().equations_`. These attributes are values that are expected to be overriden each time `.fit()` is called.
7. Docstrings are not in the perfered form.

### Potential negative consequences
The biggest issue that I can see from making these modifications is the change to where execution parameters vs model hyper-parameters are definied. I.E parameters that are currently passed to the `PySRRegressor` constructor will need to be passed to `.fit()` instead. This would require users of PySR to update their code to the new format. Similarly, the current functionality to provide backwards compaitibility with decprecated keywords would be lost. However, personally, given the potential to simplify the code and more easily support other scikit-learn functions i think the benefits outweigh the cons.

I'm really enjoying the package so far and I am more than happy to submit a pull-request for all of the above changes.

**Comment by MilesCranmer** [comment]
I do see your point about how parameters like `julia_project` and `tempdir` are runtime parameters so you might not want those passed from `get_parameters()`. For example, if I load someone's saved parameters, I wouldn't want it to use the same values for those.

However, `n_jobs` is a typical parameter in scikit-learn models, and that seems to be similar to `julia_project`, for example, in that it would depend on what machine you are running it. So maybe it's fine to keep `julia_project` and `tempdir` in `__init__`.

Thoughts?

**Comment by MilesCranmer** [comment]
Sounds good to me! I also agree that `variable_names` really makes sense to go in `.fit()`.
