### ISSUE TITLE
[BUG] *Error during installation step (python -c 'import pysr; pysr.install()' )

### ISSUE THREAD

**Issue by Carlos-Fernands** [MilesCranmer/PySR#152]
**Describe the bug**
When running the 3rd installation step for Windows: python -c "import pysr; pysr.install()",
I get the error message sequence:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jc_fe\anaconda3\lib\site-packages\pysr\__init__.py", line 2, in <module>
    from .sr import (
  File "C:\Users\jc_fe\anaconda3\lib\site-packages\pysr\sr.py", line 16, in <module>
    from sklearn.utils.validation import (
ImportError: cannot import name '_check_feature_names_in' from 'sklearn.utils.validation' (C:\Users\jc_fe\anaconda3\lib\site-packages\sklearn\utils\validation.py)

jc_fe is my user, of course.

When checking the contents of validation.py I really can't find _check_feature_names_in  there.
The sr.py contains:
   from sklearn.utils.validation import (
       _check_feature_names_in,
       check_is_fitted,
   )

and in validation.py I am able to find:
    @_deprecate_positional_args
    def check_is_fitted(estimator, attributes=None, *, msg=None, all_or_any=all):
        """Perform is_fitted validation for estimator.
but there is no reference to  _check_feature_names_in

**Version (please complete the following information):**
- OS: Windows
- Version 11
- Does the bug appear with the latest version of PySR? Yes, installed today

**Configuration**
- What are your PySR settings? No idea since this fails at installation - if I also try to run the simple example code shown for this project I get the same error
- What dataset are you running on? This happens before any run.

**Error message**
See traceback above; key error message is: 
ImportError: cannot import name '_check_feature_names_in' from 'sklearn.utils.validation' (C:\Users\jc_fe\anaconda3\lib\site-packages\sklearn\utils\validation.py)

If the error is "Couldn't find equation file...", this error indicates something
went wrong with the backend. Please scroll up and copy 
the output of Julia, rather than the output of python.

**Additional context**
I just followed the (Windows) steps for the installation and as per above it fails on the third one.

**Comment by MilesCranmer** [comment]
Update scikit-learn with: `pip install -U scikit-learn`. That function was only added for sklearn > 1.0

**Comment by MilesCranmer** [comment]
I just added `scikit-learn >= 1.0.0` to the pip requirements so this shouldn't appear for others in the future.

Cheers,
Miles

**Comment by Carlos-Fernands** [comment]
Thank you - upgrading sklearn to 1.1.1 fixed it
