### ISSUE TITLE
[BUG] Procs parameter seems to be ignored

### ISSUE THREAD

**Issue by Carlos-Fernands** [MilesCranmer/PySR#154]
**Describe the bug**
I have 16 threads (8 cores) , but although I've been playing with the procs parameter I never seem to be using more than a fixed number (2, given the ~12.5% of CPU I mostly get). 

I ran the code in the README.md file and all runs OK; I added the procs parameter to the first example, with values 1,2,4,8,16 and this makes no difference whatsoever in terms of the CPU usage - always the same ~12.5% (2 threads/1 core). They all take about the same time, roughly 20-21 seconds.

The second piece of code includes procs = 4 but again the CPU usage is the same as before (above).

**Version (please complete the following information):**
- OS: Windows
- Version 11
- Does the bug appear with the latest version of PySR? Yes, installed yesterday

**Configuration**
- What are your PySR settings? Just those in the examples in the README file

**Comment by MilesCranmer** [comment]
What Julia version, Python version, PySR version?

Does the result change if you set `multithreading=False` in `PySRRegressor`? This will switch to a different backend for parallel processing so this would be helpful to debug it.

**Comment by Carlos-Fernands** [comment]
Julia version = 1.7.3
Python version = 3.8.8
PySR version =  0.9.3

Adding multithreading=False does make a difference and I can see the CPU finally increase in use.
With procs = 2 I can see the 2 instances of Julia Programming Language running, and so on.
The funny thing is that I can't see linear improvements: 6 cores takes about the same time as 4, for example. 8 cores takes more time than 4.
Could there be some caching at play? Or that this code really does not benefit from multi-cores? (Which looks unlikely.)

From my tests procs is really related to the actual number of physical cores, not to the number of logical processors (as I was expecting, from how sklearn works).
Why? Because if I set procs to a number greater than my 8 cores:  
  1- the code crashes on some Julia calls
  2- the environment related to PySRRegressor becomes unstable and even re-running with a lower, valid, number for procs it continues to crash. I had to shutdown the whole session and restart.

I would suggest for the PySR code to check the number assigned to procs and if greater than the physical number of cores present either stop and issue an error message or issue a warning, setting procs to the max possible and continue.

Adding multithreading=False to the second piece of code again "helps", as I can see the CPU jumping from ~12% to about 55%, like in the first case (with procs = 8, when I would expect CPU about 100%,  )

**Comment by MilesCranmer** [comment]
Thanks, that test is really helpful. So something about your configuration is not setting up Julia to be multi-threaded, but multi-processing works.

What operating system are you using? I wonder if the environment variable for Julia on your system is different. The env variable is normally `JULIA_NUM_THREADS`.

**Comment by Carlos-Fernands** [comment]
I am running Windows 11 Home (version 21H2, build 22000.739)
And I don't seem to have an environment variable called JULIA_NUM_THREADS or similar.
In the environment variables the only reference to Julia is as part of the path:  ...\Julia-1.7.3\bin

So I set it, with JULIA_NUM_THREADS = 14 (just to be safe as I've seen other very "efficient" processes freezing the computer when using threads = max possible).

I had to restart Anaconda because it didn't seem to pick up the new variable immediately .

After that, setting procs = 14 and removing  multithreading=False,...
The first piece of code reduced from 1' 20''  to 20''.
In the second more complex example again I saw the processor going from the previous ~50% to about 65% - not the 80-90% I was expecting, but still better.

In both cases I did not see instances of "Julia Programming Language" task as before, but just a Python instance doing all the work.

So, yes,  I think the absence of that environment variable was the problem - thank you!.

In the installation process I remember being asked if I wanted access just for myself (i.e. my account) or for all users in the computer - I answered just me and now I am wondering if this was why that env. variable was not set (although both things should be totally independent). When I have time I'll reinstall the whole thing for all users and check if something changed about this.

**Comment by MilesCranmer** [comment]
I am a bit confused, because `JULIA_NUM_THREADS` should be set within PySR automatically: https://github.com/MilesCranmer/PySR/blob/6ed57c829fe606e5a7b3d63880477e0f7dbb3af4/pysr/sr.py#L1304. I wonder why this is not working on your system? Maybe it's because it's windows...?

**Comment by MilesCranmer** [comment]
Can you try doing this again without the env variable, and trying to call `os.environ["JULIA_NUM_THREADS"] = str(self.procs)` manually?

**Comment by Carlos-Fernands** [comment]
When you say manually, I assume this  means running that line included in Python code?

**Comment by MilesCranmer** [comment]
Correct

**Comment by Carlos-Fernands** [comment]
After adding the line    
**os.environ["JULIA_NUM_THREADS"] = str(self.procs)**
immediately before 
**pysr import PySRRegressor**
I get:
**NameError: name 'self' is not defined**

**Comment by MilesCranmer** [comment]
Don’t use `self.procs`, just write the number of procs you want…

**Comment by MilesCranmer** [comment]
Anyways it sounds like this issue was solved on your OS by setting JULIA_NUM_THREADS globally, so I will close this. 
cheers,
Miles

**Comment by Carlos-Fernands** [comment]
Tried that too - no difference.
Anyway, sorted, thanks.
