### ISSUE TITLE
[BUG] AttributeError in variable_names check

### ISSUE THREAD

**Issue by EvilMav** [MilesCranmer/PySR#162]
`[" " in name for name in variable_names].any()` leads to `AttributeError: 'list' object has no attribute 'any'` for me.

https://github.com/MilesCranmer/PySR/blob/edb2cd636d2b052fbc13d18a33f768c869e3aa13/pysr/sr.py#L1136

**Comment by MilesCranmer** [comment]
Thanks, that's definitely a bug. Will fix!

**Comment by MilesCranmer** [comment]
Fixed :)
