### ISSUE TITLE
[BUG] Error executing example program on Ubuntu 20.04

### ISSUE THREAD

**Issue by diegobonilla98** [MilesCranmer/PySR#174]
There is an error that prevents the execution of the example program.

- OS: Ubuntu 20.04
- Julia version 1.4.1
- Python version 3.7.7
- PySR version 0.9.5
- Does the bug still appear with the latest version of PySR? YES

The code is the example provided in the README.md of the project. Copy and pasted. I've followed and redone all the installation steps a bunch of times and nothing... :(

ERROR:

 Activating environment at `~/.julia/environments/pysr-0.9.5/Project.toml`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
julia version requirement for package `SymbolicRegression [8254be44]` not satisfied
   Updating `~/.julia/environments/pysr-0.9.5/Project.toml`
 [no changes]
   Updating `~/.julia/environments/pysr-0.9.5/Manifest.toml`
 [no changes]
  Resolving package versions...
julia version requirement for package `SymbolicRegression [8254be44]` not satisfied
   Updating `~/.julia/environments/pysr-0.9.5/Project.toml`
 [no changes]
   Updating `~/.julia/environments/pysr-0.9.5/Manifest.toml`
 [no changes]
julia version requirement for package `SymbolicRegression [8254be44]` not satisfied
   Updating `~/.julia/environments/pysr-0.9.5/Project.toml`
 [no changes]
   Updating `~/.julia/environments/pysr-0.9.5/Manifest.toml`
 [no changes]
┌ Warning: the implicit keyword argument `filter_modules=(:Base, :SpecialFunctions, :NaNMath)` in `diffrules()` is deprecated and will be changed to `filter_modules=nothing` in an upcoming breaking release of DiffRules (i.e., `diffrules()` will return all rules defined in DiffRules)
│   caller = top-level scope at number.jl:6
└ @ Core ~/.julia/packages/Zygote/DkIUK/src/forward/number.jl:6
┌ Warning: the implicit keyword argument `filter_modules=(:Base, :SpecialFunctions, :NaNMath)` in `diffrules()` is deprecated and will be changed to `filter_modules=nothing` in an upcoming breaking release of DiffRules (i.e., `diffrules()` will return all rules defined in DiffRules)
│   caller = top-level scope at number.jl:14
└ @ Core ~/.julia/packages/Zygote/DkIUK/src/forward/number.jl:14
Traceback (most recent call last):
  File "/home/bonilla/Desktop/PythonProjects/PhysicsSystemDeepModeling/SR_PySR.py", line 25, in <module>
    model.fit(X, y)
  File "/home/bonilla/.local/lib/python3.7/site-packages/pysr/sr.py", line 1607, in fit
    return self._run(X, y, mutated_params, weights=weights, seed=seed)
  File "/home/bonilla/.local/lib/python3.7/site-packages/pysr/sr.py", line 1336, in _run
    Main.eval("using SymbolicRegression")
  File "/home/bonilla/.local/lib/python3.7/site-packages/julia/core.py", line 621, in eval
    ans = self._call(src)
  File "/home/bonilla/.local/lib/python3.7/site-packages/julia/core.py", line 549, in _call
    self.check_exception(src)
  File "/home/bonilla/.local/lib/python3.7/site-packages/julia/core.py", line 604, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'LoadError: LoadError: LoadError: LoadError: syntax: invalid keyword argument syntax "Fs"
in expression starting at /home/bonilla/.julia/packages/SymbolicUtils/qulQp/src/polyform.jl:124
in expression starting at /home/bonilla/.julia/packages/SymbolicUtils/qulQp/src/SymbolicUtils.jl:49
in expression starting at /home/bonilla/.julia/packages/SymbolicRegression/LG35p/src/InterfaceSymbolicUtils.jl:3
in expression starting at /home/bonilla/.julia/packages/SymbolicRegression/LG35p/src/SymbolicRegression.jl:103' occurred while calling julia code:
using SymbolicRegression

**Comment by MilesCranmer** [comment]
Your Julia version is out-of-date - it should be 1.6 or higher for PySR to work I think.

**Comment by diegobonilla98** [comment]
Yes! That worked. Thank you very much!
