### ISSUE TITLE
[BUG] Julia updating even when `update=False`

### ISSUE THREAD

**Issue by aminravanbakhsh** [MilesCranmer/PySR#185]
Hi, I hope you are doing well.
I used PySR to solve the example on the PySR github page. However, each time I run the code, it upgrades Julia. I would appreciate it if you could tell me what the problem is. It is worth mentioning that I use a virtual environment for my code. You can see the results below.

Version (please include the following information):
- OS: Ubuntu: 20.04.4
- Julia version: 1.6.7
- Python version: 3.9.12
- PySR version: 0.10.1

![Screenshot from 2022-09-04 18-59-58](https://user-images.githubusercontent.com/33625204/188320203-c7b54cc6-6501-4713-9a1b-71b303b02c16.png)
![Screenshot from 2022-09-04 18-58-18](https://user-images.githubusercontent.com/33625204/188320210-202efc2a-88b5-4079-864d-6574bad2fd3a.png)

**Comment by MilesCranmer** [comment]
Hi @aminravanbakhsh,
This is normal behaviour. It is updating packages, not updating Julia itself. 

You can disable this behaviour with `update=False`.

Also note that this only occurs the first time you run `fit(X, y)` in a Python process. Subsequent calls will not do this. If you quit and re-open Python, it will happen again. 

Best,
Miles

**Comment by aminravanbakhsh** [comment]
Hi Miles,
Thanks for your response. However, I used "update = False" and it didn't work. Do you have any other ideas about this?

Regards,
Amin

**Comment by aminravanbakhsh** [comment]
Thanks for your attention.
Unfortunately it didn't work for me. Do you have any other ideas?

**Comment by aminravanbakhsh** [comment]
Unfortunately it didn't work too. 
I tried to reinstall the PySR. I received this warning, maybe it could help.

![Screenshot from 2022-09-06 12-16-31](https://user-images.githubusercontent.com/33625204/188579869-41068a4a-9014-4061-8168-95b0cf61c6bd.png)

**Comment by MilesCranmer** [comment]
@aminravanbakhsh can you be more specific about what’s not working? From my test it seems like everything is good to go.

**Comment by aminravanbakhsh** [comment]
I am just saying that every time I run the code, it updates the registry, even when I reinstalled the PySR. I am just using a virtual environment on my Ubuntu 20.04.

**Comment by aminravanbakhsh** [comment]
Thanks for your helps Miles! It worked and I didn't receive the update message. However, it took a lot of time to start the process. Is it OK? Moreover, I am interested in how PySR works. Is there any paper that describes the PySR algorithm?
