### ISSUE TITLE
Hall of fame output cannot be turned off?

### ISSUE THREAD

**Issue by johannbrehmer** [MilesCranmer/PySR#19]
Hi,

I haven't found any switch to reduce or turn off the printing of the current hall of fame.

Would it be possible to expose `print_every_n_seconds`, or give the user some other option to modify this?

Thanks,
Johann

**Comment by MilesCranmer** [comment]
Hey Johann,

Good point! I have a "verbosity" argument to `pysr`, but this actually doesn't affect the printing of the hall of fame right now.

I've just added it to master. Now, `verbosity=0` will turn off hall of fame printing.

Cheers,
Miles

**Comment by johannbrehmer** [comment]
Thanks, that was quick!
