### ISSUE TITLE
[BUG] SymbolicRegressions.jl is not installed into julia_project

### ISSUE THREAD

**Issue by mkitti** [MilesCranmer/PySR#196]
**Describe the bug**

Due to following lines, SymbolicRegressions.jl does not get installed into an environment indicated by the `julia_project` argument of `pysr.install`. `is_shared` is always false when `julia_project` is not `None`.

https://github.com/MilesCranmer/PySR/blob/b6ac303316bf72dbf49f29418c519e6dd2f120d9/pysr/julia_helpers.py#L89-L91

It's not clear to me why SymbolicRegressions.jl should only be installed into a shared environment. I think this may just be left over logic when it was being installed into a temporary directory. My thought is that we should remove the if statement.

**Comment by mkitti** [comment]
Also this would be nice if we checked if the first character is `@` and marked it as `is_shared` in that case.

**Comment by MilesCranmer** [comment]
> It's not clear to me why SymbolicRegressions.jl should only be installed into a shared environment. I think this may just be left over logic when it was being installed into a temporary directory. My thought is that we should remove the if statement.

The other use-case for the `julia_project` is to point to a development version of SymbolicRegression.jl. If we remove that if statement, then we get this error:
```julia
    Updating registry at `~/.julia/registries/General.toml`
ERROR: package `SymbolicRegression [8254be44]` has same name or UUID as the active project
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
 [2] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
   @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:268
 [3] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:156
 [4] add(pkgs::Vector{Pkg.Types.PackageSpec})
   @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:145
 [5] #add#26
   @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:143 [inlined]
 [6] add(pkg::Pkg.Types.PackageSpec)
   @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:143
 [7] top-level scope
   @ REPL[3]:1
```

> Also this would be nice if we checked if the first character is @ and marked it as is_shared in that case.

This is a good idea! Will add.

**Comment by mkitti** [comment]
> The other use-case for the `julia_project` is to point to a development version of SymbolicRegression.jl. If we remove that if statement, then we get this error:

I'm a bit confused about what you're trying to do that causes this. It sounds like you set `julia_project = "/path/to/SymbolicRegression.jl"`. Then, yes trying to add SymbolicRegression.jl to it's own environment would cause the above error.

To avoid this, I might check `Pkg.project().uuid == Base.UUID("8254be44-1295-4e6a-a16d-46603ac705cb")`. In that case though, `ClusterManagers.jl` may not be available.

The other path would be to create a `pysr.julia_helpers.develop` function that does the following.
1. Creates and activates a temporary environment
2. `Pkg.develop("/path/to/SymbolicRegression.jl")`
3. `Pkg.add("ClusterMangagers")`
