### ISSUE TITLE
[BUG] conda version breaking

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#201]
Edit: If you are seeing issues with the conda version, try setting `update=False` when initializing `PySRRegressor`.

---

The conda-forge jobs which test `conda install -c conda-forge pysr` are currently breaking. This is even with repeat attempts: https://github.com/MilesCranmer/PySR/actions/workflows/CI_conda_forge.yml.
The error:
```
ImportError: 
    Required dependencies are not installed or built.  Run the following code in the Python REPL:
```

I find this strange, since underlying feedstock has not changed in the meantime, and it seems like the julia feedstock hasn't been updated recently either. 

FYI @mkitti @ngam. I will try to look into this a bit later today.

**Comment by MilesCranmer** [comment]
Seems like I can install it locally just fine, so I guess it is specifically an issue with the CI? Perhaps the latest GitHub action for `miniforge` is doing something weird.

**Comment by MilesCranmer** [comment]
Tried with the regular miniconda install, and still seems broken. Here's the action log: https://github.com/MilesCranmer/PySR/actions/workflows/CI_conda_forge.yml

and here's the GitHub action: https://github.com/MilesCranmer/PySR/blob/fix-conda-forge/.github/workflows/CI_conda_forge.yml.

It just runs `conda create -n test -c conda-forge pysr` but can't seem to locate the Julia deps... I'm not sure what's going wrong.

**Comment by MilesCranmer** [comment]
@mkitti @ngam does the conda install of PySR still work for you? It seemed to work when I tried it, but now I'm a bit suspicious that it was trying to use the existing Julia depot.

**Comment by MilesCranmer** [comment]
(I think the first error is because the `python -m unittest test.test` needs to be run from the root folder)

This other issue is interesting:
```
julia.core.JuliaError: Exception 'expected package `GPUArraysCore [46192b85]` to be registered' occurred while calling julia code:
```
Is this because the shipped depot doesn't contain this package, and an updated package version requests it?

**Comment by MilesCranmer** [comment]
I wonder if this is caused by PySR's default behavior being to update the Julia project... Maybe that should be disabled for the conda version?

**Comment by MilesCranmer** [comment]
I think this is because the new build is now including GPUArraysCore in the depot, so everything is fine now? However, whenever a new dependency is introduced, the same error will come up since the default PySR behavior is to update the Julia project - and that new dependency won't be in the depot until we re-render it.

I'll set `update=False` on conda versions of PySR to fix this. Is there a way to check, within PySR itself, whether it is installed as the pip version or the conda version?

**Comment by MilesCranmer** [comment]
> Shouldn't a version be completely static (at least for pysr and SymbolicRegression.jl)?

I think so too (in hindsight). Right now it does an update (with `Pkg.resolve()`) every time `fit` is called:

https://github.com/MilesCranmer/PySR/blob/134a0cdb767f63c586e2a4e9c4ebad37ce4a39f5/pysr/sr.py#L1469-L1473

Should I just set `update=False` as the default?

(Note for myself... If `update=False`, would people need to re-run `pysr.install()` if `pysr` is updated through pip? I think otherwise, the right env wouldn't be created.)

**Comment by MilesCranmer** [comment]
Will do - I will just set `update=False`. I think this is better even for pip. The worst would be if a user is running something, and some dependency breaks everything (without them even updating it explicitly), and suddenly their code doesn't work without them knowing why. I am guessing some conda PySR users unfortunately experienced this, so having `update=False` would prevent this in the future.

**Comment by MilesCranmer** [comment]
Indeed, with https://github.com/conda-forge/pysr-feedstock/pull/55 merged, the conda builds are now working again: https://github.com/MilesCranmer/PySR/actions/runs/3216137165/jobs/5257733071. The only meaningful difference is that the depot was re-built, and now GPUArraysCore is included.

**Comment by MilesCranmer** [comment]
By the way, any idea how to remove the warning printouts from the conda version?
e.g.,
```
WARNING: method definition for dpeekbyte at /home/ngam/.Mambaforge-Linux-x86_64/envs/test/share/pysr/depot/packages/Parsers/34hDN/src/utils.jl:199 declares type variable T but does not use it.
```
I don't see this with a normal installation of Julia.

**Comment by MilesCranmer** [comment]
@ngam do you think you could run a quick test for me on your machine? In your (currently-broken) version of PySR, could you run this command?
```bash
python -c 'import numpy as np; from pysr import PySRRegressor; X = np.random.randn(100,1); y = X[:, 0]**3; PySRRegressor(update=False).fit(X, y).predict(X)'
```
I just want to make sure that `update=False` will prevent this type of issue from happening in the future.

**Comment by MilesCranmer** [comment]
It seems like Julia is being initialized with some of the `warn` flags still active. My bet is that the conda activate file sets a few env variables that turn warnings on (maybe for debugging, but they were never removed?)?

**Comment by MilesCranmer** [comment]
Maybe the `julia-feedstock` repo is the cause of this, actually?

**Comment by MilesCranmer** [comment]
@ngam I realized these warning messages are just from new versions of Julia - they print out at the pre-compilation step. (I see them even when running pure Julia.)

If PySR is using a custom Julia depot, is there anything that would prevent precompilation from being cached?

**Comment by mkitti** [comment]
Each depot has its own `compiled` folder. Changing depots means changing precompilation caches.
