### ISSUE TITLE
[BUG] Installation failure at "juliainfo.py" with "subprocess.CalledProcessError"

### ISSUE THREAD

**Issue by Zhonglu** [MilesCranmer/PySR#224]
**Describe the bug**
Installation failure with "subprocess.CalledProcessError"

I installed julia in WSL Ubuntu by command line.
Then, run: pip install -U pysr
Yet, python -c 'import pysr; pysr.install()'  did not work.
Please see error message below.

**Version (please include the following information):**
- OS: Win 10, WSL2, Ubuntu 20.04
- julia version 1.4.1
-  Python 3.8.10
- pip
- PySR version 0.11.9
- Does the bug still appear with the latest version of PySR?       Yes

**Configuration**
- What are your PySR settings?      Still installing
- What dataset are you running on?      NA
- If possible, please share a minimal code example that produces the error.      NA

**Error message**
Add the error message here, or whatever other information would be useful for debugging.
log below:
~/pysr$ python3 -c 'import pysr; pysr.install()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/flyme2004/.local/lib/python3.8/site-packages/pysr/julia_helpers.py", line 74, in install
    _julia_version_assertion()
  File "/home/flyme2004/.local/lib/python3.8/site-packages/pysr/julia_helpers.py", line 223, in _julia_version_assertion
    if not is_julia_version_greater_eq(version=(1, 6, 0)):
  File "/home/flyme2004/.local/lib/python3.8/site-packages/pysr/julia_helpers.py", line 122, in is_julia_version_greater_eq
    juliainfo = _load_juliainfo()
  File "/home/flyme2004/.local/lib/python3.8/site-packages/pysr/julia_helpers.py", line 23, in _load_juliainfo
    juliainfo = JuliaInfo.load(julia="julia")
  File "/home/flyme2004/.local/lib/python3.8/site-packages/julia/juliainfo.py", line 87, in load
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1.

**Additional context**
I have searched the issue log, yet could not find any clue. Appreciate any comment. Looking forward to apply PySR in my new paper.

**Comment by Zhonglu** [comment]
testing newer version of julia

**Comment by MilesCranmer** [comment]
Looks like it can’t find the location of Julia. Check your PATH variable?

**Comment by MilesCranmer** [comment]
> julia version 1.4.1

this also won’t work, you need Julia 1.6 or higher

**Comment by MilesCranmer** [comment]
(Didn’t mean to close)

**Comment by Zhonglu** [comment]
export JULIA_PKG_SERVER="https://mirrors.bfsu.edu.cn/julia"

**Comment by MilesCranmer** [comment]
Awesome! Glad to hear it’s working.
