### ISSUE TITLE
[BUG] Colab broken on current Julia version

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#259]
Related to #249 

When I run the current colab notebook, I can't even get past the Julia install step.

```
Installing Julia 1.7.2 on the current Colab Runtime...
2023-01-30 19:40:18 URL:https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.2-linux-x86_64.tar.gz [123295596/123295596] -> "/tmp/julia.tar.gz" [1]
Installing PyCall.jl...
  Installing known registries into `~/.julia`
free(): invalid pointer

signal (6): Aborted
in expression starting at none:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
```

Thanks to @jwuphysics for mentioning this!

**Comment by MilesCranmer** [comment]
Seems like all Julia installations are currently breaking on Colab:

- https://github.com/JuliaLang/julia/issues/48461
- https://discourse.julialang.org/t/google-colab-compatibility-broken/93004/9

**Comment by fitriaramlan** [comment]
I think the colab broken is still happening?

**Comment by MilesCranmer** [comment]
This should be fixed by https://github.com/googlecolab/colabtools/issues/3385.

Not sure what errors you are seeing @fitriaramlan; the current colab notebook runs fine for me: https://colab.research.google.com/github/MilesCranmer/PySR/blob/master/examples/pysr_demo.ipynb

**Comment by fitriaramlan** [comment]
Thanks @MilesCranmer. I was still using the previous code on the first cell. but now it runs well for me too.

**Comment by MilesCranmer** [comment]
Great!
