### ISSUE TITLE
weight_optimize not a valid argument for regressor

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#279]
### Discussed in https://github.com/MilesCranmer/PySR/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **krn-hov** March 15, 2023</sup>
When I try and set the weight_optimize parameter I get the 
TypeError: weight_optimize is not a valid keyword argument for PySRRegressor.
The regressor should update automatically I thought, in case this should be a version issue. But yes, I am curious if others are able to set this parameter. Especially since I want to use a large ncyclesperiteration.</div>

**Comment by MilesCranmer** [comment]
@krn-hov what PySR version?

**Comment by krn-hov** [comment]
I am running version 0.11.6

**Comment by MilesCranmer** [comment]
Closing this as it appears to be a version issue. Don't hesitate to reopen if still giving problems!

Cheers,
Miles
