### ISSUE TITLE
Custom loss function

### ISSUE THREAD

**Issue by ythrandir** [MilesCranmer/PySR#29]
Hi,

Is it possible to have the example.py show how to build a custom loss function? I'm still unable to figure out how to do it from the codes.

Thanks!

**Comment by MilesCranmer** [comment]
Hey @ythrandir, sure, I can add something to the `example.py`.

Also, this made me realize that the docs are not updating. The new docs were supposed to have examples of `loss`, but this is not compiling for some reason. Here is the fixed version! https://pysr.readthedocs.io/en/latest/docs/options/#loss. 

I will add a couple other examples to that section to make it easier to set up.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Alright, here's the new loss page! Let me know if you have any other questions.

<img width="767" alt="Screen Shot 2021-02-16 at 11 45 23 AM" src="https://user-images.githubusercontent.com/7593028/108094109-76546580-704c-11eb-8838-bfed4acbcb50.png">

Cheers,
Miles
