### ISSUE TITLE
Additional export options

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#32]
@patrick-kidger has written an amazing SymPy->PyTorch export library https://github.com/patrick-kidger/sympytorch. Will be really nice to use this in PySR, so that equations can be directly exported to PyTorch!

Also might be nice to have a JAX export too - e.g., could export a function that takes `(x, parameters)` as arguments (in traditional JAX functional style...).

**Comment by MilesCranmer** [comment]
Update: got a JAX one working: https://github.com/MilesCranmer/sympy2jax.

This is also built into PySR now (optional import). You can say `output_jax_format=True`, and it will give you another column of the equations dataframe with JAX callables and default parameters in a jax numpy array.

@patrick-kidger - I guess for the PyTorch equivalent, it should output a module? What do you think?

**Comment by patrick-kidger** [comment]
Based on a quick glance, sympy2jax looks good. I note that it doesn't have a reverse JAX->SymPy option though.

Is having it as another option like that really the cleanest interface? (And a violation of SSOT.) There's already all of `best`, `best_latex`, `best_callable` etc. Perhaps always give the user an expression object with some methods:

```python
class Expresion:
    def __init__(self, *, sympy_expr, **kwargs):
        super().__init__(**kwargs)
        self.sympy_expr = sympy_expr
    def as_sympy():
        return self.sympy_expr
    def as_jax():
        return sympy2jax(self.sympy_expr)
    def as_pytorch():
        return sympytorch.SymPyModule(expressions=[sympy_expr])
    def as_latex():
        ...
```

For PyTorch I agree that outputting modules sounds appropriate. (Conveniently what sympytorch already does.)
