### ISSUE TITLE
Planned breaking changes in v0.6.0

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#33]
Will continue to update this issue until v0.6.0 released.

- [x] New defaults:
  - annealing=False (no annealing works better with the new code. This is equivalent to alpha=infinity)
  - useFrequency=True (deals with complexity in a smarter way)
  - npopulations = 20 ~~procs*4~~
  - progress=True (show a progress bar)
  - optimizer_algorithm="BFGS"
  - optimizer_iterations=10
  - optimize_probability=1
  - binary_operators default = ["+", "-", "/", "*"]
  - unary_operators default = []
- [x] Warnings:
  - Using maxsize > 40 will trigger a warning mentioning how it will be slow and use a lot of memory. Will mention to turn off `useFrequency`, and perhaps also use `warmupMaxsizeBy`.
- [x] Deprecated nrestarts -> optimizer_nrestarts
- [x] Exports to JAX, PyTorch, NumPy unified into same function call: pass X[nrows, features] as single argument, rather than the current numpy one which is different arguments for each feature. JAX export will optionally take parameters as arguments (for training). The PyTorch output is a trainable module (thanks @patrick-kidger!)
- [x] Custom constant optimizer: can choose between NelderMead and BFGS (requires differentiable operators).
- [x] Test progress bar in jupyter
- [x] Decide if should change format away from pandas dataframe to something like Patrick suggested, with a custom class for equations, containing `.to_sympy`, `.to_numpy`, etc. Downside is one can't do the `.query()`, `.sort_values()`, `.plot()`, etc., that come with Pandas.
  - (Not doing for now)

**Comment by patrick-kidger** [comment]
> npopulations = procs*4 (more populations = better)

I'm not so sure about this one. `npopulations` is a modelling parameter, but `procs` ias an implementation parameter. For example if I switch to a weaker machine, and set a small `procs` as a result, I'd be a bit surprised to find that the optimisation has silently changed as well.

Other than that, looks very good!

**Comment by MilesCranmer** [comment]
Thats a good point. I think I will fix default npopulations at 20 in v0.6 instead.

**Comment by MilesCranmer** [comment]
I'm tempted to make BFGS the default optimizer. The only issue is it might not get great results on discontinuous functions. However, there is still the mutations which happen for those cases (and I'm not sure NelderMead would do better anyways).

**Comment by MilesCranmer** [comment]
Pushed new defaults to master! Will need to add the pytorch export, unify with the numpy and jax modules, then it should be ready to push to PyPI.

**Comment by MilesCranmer** [comment]
All changes implemented and tested. v0.6.0 is live and on PyPI.
