### ISSUE TITLE
BoundsError in custom eval_tree_array

### ISSUE THREAD

**Issue by DenisSvirin** [MilesCranmer/PySR#337]
### What happened?

I tried to run '_eval_tree_array'  with array that has different dimensions then cX in 'eval_tree_array'

And if i understand correctly after test runs l've got an error ''

### Version

0.18.0

### Operating System

macOS

### Interface

Jupyter Notebook

### Relevant log output

```shell
BoundsError: attempt to access 1×11 Matrix{Float32} at index [4, 1:11]
```

### Extra Info

my version of 'eval_tree_array' :
```
function eval_tree_array(
    tree::Node{T}, cX::AbstractMatrix{T}, operators::OperatorEnum; turbo::Bool=false
)::Tuple{AbstractVector{T},Bool} where {T<:Number}
    if turbo
        @assert T in (Float32, Float64)
    end
    r = T.( [6.332061275761631 5.051237472144821 2.7 4.2690748412273125 3.3068111527572905 5.4 4.676537180435969 6.037383539249433 5.727564927611035 3.8183$
    result, finished = _eval_tree_array(
        tree, r, operators, (turbo ? Val(true) : Val(false))
    )
  
           
    @return_on_false finished result
    @return_on_nonfinite_array result  
    return result, finished
end
```

**Comment by DenisSvirin** [comment]
precompilation works fine, it  occurs during search.

Oh, then i'll try it this way.

**Comment by MilesCranmer** [comment]
So the bug is fixed with this change?

**Comment by DenisSvirin** [comment]
yes, if i do it with full_objective

**Comment by MilesCranmer** [comment]
Great! 

It's probably because there are other pieces of code that rely on `eval_tree_array`. It is a generic function for evaluating an expression and shouldn't be overloaded. `eval_loss` is for these purposes (which is what `full_objective` overrides).
