### ISSUE TITLE
[BUG]: SymPy parsing error related to unicode encodings on Windows

### ISSUE THREAD

**Issue by Imageman** [MilesCranmer/PySR#395]
### What happened?

When start standart example on Windows 10 or 7 (russian) and get the following result:
`
-----------------------------------------------------------------------------------------------------------------------
ValueError: Error from parse_expr with transformed code: "(Symbol ('xв' )‚Symbol ('Ђ' )*Symbol ('xв' )‚Symbol ('Ђ' ))"-
-----------------------------------------------------------------------------------------------------------------------
The above exception was the direct cause of the following exception:s(sin(0.80486))) + cos(x₃))) + cos(x₃))
18          1.710e+01  1.633e-03  y = ((exp(1.0925) + ((sin(x₃) * cos(0.80486)) + cos(x₃))) + ((cos(x₃) + -0.18981) ...
Traceback (most recent call last):* 1.0925))

`

As I understand in some place X0 is encoded with a unicode character, which then causes an error in sympify.

![изображение](https://github.com/MilesCranmer/PySR/assets/2051167/5614bdc2-d29a-41ab-bdfb-5830d5c4093f)

Python Conda and PySR installed via pip

### Version

0.15.1

### Operating System

Windows

### Package Manager

pip

### Interface

Script (i.e., `python my_script.py`)

### Relevant log output

```shell
d:\tmp\1>python 1.py
Compiling Julia backend...
Started!
99.3%┣██████████████████████████████████████████████████████████████████████████████████▌┫ 596/600 [00:08<00:00, 75it/s]Expressions evaluated per second: 1.75e+05. Head worker occupation: 9.3%                                                Press 'q' and then <enter> to stop execution early.                                                                     Hall of Fame:                                                                                                           ----------------------------------------------------------------------------------------------------------------------- Complexity  Loss       Score     Equation                                                                               1           2.182e+01  1.748e-07  y = 3.3563                                                                            2           2.182e+01  5.950e-08  y = exp(1.2108)                                                                       3           3.038e+00  1.972e+00  y = (x₀ * x₀)                                                                         5           3.005e+00  5.379e-03  y = ((x₀ * x₀) * 1.034)                                                               6           1.158e+00  9.534e-01  y = ((x₀ * x₀) + cos(x₃))                                                             8           2.321e-01  8.038e-01  y = ((x₀ * x₀) + (cos(x₃) * 2.3505))                                                  10          3.398e-11  1.106e+01  y = (((x₀ * x₀) + -0.50001) + (cos(x₃) * 2.5382))                                     12          1.291e-13  2.787e+00  y = (((x₀ * x₀) + (0.035496 + -0.5355)) + (cos(x₃) * 2.5382))                         -----------------------------------------------------------------------------------------------------------------------
ValueError: Error from parse_expr with transformed code: "(Symbol ('xв' )‚Symbol ('Ђ' )*Symbol ('xв' )‚Symbol ('Ђ' ))"-
-----------------------------------------------------------------------------------------------------------------------
The above exception was the direct cause of the following exception:s(sin(0.80486))) + cos(x₃))) + cos(x₃))
18          1.710e+01  1.633e-03  y = ((exp(1.0925) + ((sin(x₃) * cos(0.80486)) + cos(x₃))) + ((cos(x₃) + -0.18981) ...
Traceback (most recent call last):* 1.0925))
  File "c:\ProgramData\Anaconda3\lib\site-packages\sympy\core\sympify.py", line 495, in sympify5))) + sin(cos(x₃) * ...
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "c:\ProgramData\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py", line 1087, in parse_expr------------
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "c:\ProgramData\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py", line 1078, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "c:\ProgramData\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py", line 906, in eval_expr
    expr = eval(
  File "<string>", line 1
    (Symbol ('xв' )‚Symbol ('Ђ' )*Symbol ('xв' )‚Symbol ('Ђ' ))
                         ^
SyntaxError: invalid character in identifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "1.py", line 25, in <module>
    model.fit(X, y)
  File "c:\ProgramData\Anaconda3\lib\site-packages\pysr\sr.py", line 1965, in fit
    self._run(X, y, mutated_params, weights=weights, seed=seed)
  File "c:\ProgramData\Anaconda3\lib\site-packages\pysr\sr.py", line 1816, in _run
    self.equations_ = self.get_hof()
  File "c:\ProgramData\Anaconda3\lib\site-packages\pysr\sr.py", line 2311, in get_hof
    eqn = sympify(eqn_row["equation"], locals=local_sympy_mappings)
  File "c:\ProgramData\Anaconda3\lib\site-packages\sympy\core\sympify.py", line 497, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '(xв‚Ђ * xв‚Ђ)'' failed, because of exception being raised:
SyntaxError: invalid character in identifier (<string>, line 1)

d:\tmp\1>
```

### Extra Info

Julia 1.9.2

**Comment by MilesCranmer** [comment]
Thanks very much for the bug report. Looks like an encoding issue. Could you please share the contents of the csv file it generates? I want to know if the encoding issue happens when reading the csv file or when writing it.

A temporary workaround is for you to set the `variable_names` parameter when calling `fit`.

**Comment by MilesCranmer** [comment]
I wonder if it has to do with the csv file being saved as English encoding and then read with Russian encoding or something like that. Maybe a Russian unicode alphabet has the subscripted integers at different binary representations.

**Comment by Imageman** [comment]
[hall_of_fame_2023-08-01_191647.197.csv](https://github.com/MilesCranmer/PySR/files/12232707/hall_of_fame_2023-08-01_191647.197.csv)
csv file is UTF-8 encoding. But if read csv file as ASCII file, then visible "artefacts".
![изображение](https://github.com/MilesCranmer/PySR/assets/2051167/6ecbf555-10de-4381-bc63-a5f8263773d5)

**Comment by MilesCranmer** [comment]
I see, thank you. So if you were to open that csv with UTF-8 encoding, those characters are read correctly? Or is it written in the wrong encoding (by Julia?)

**Comment by Imageman** [comment]
> set the variable_names parameter when calling fit.
Working, thanks.

csv and bkup files in correct utf-8 encoding. 
![изображение](https://github.com/MilesCranmer/PySR/assets/2051167/46fbeafb-9936-43d6-ba2e-dde793351458)

**Comment by MilesCranmer** [comment]
@Imageman I tried to fix this in #396, would you be able to test it for me and make sure it fixes it? You can install that version with:

```
pip install git+https://github.com/MilesCranmer/PySR.git@encoding-fix
python -m pysr install
```

and then run the example normally (without passing variable_names).

What I think happened is that apparently Python's `open` can assume different encodings on different operating systems, whereas Julia always writes with UTF-8. So it was not able to read things correctly.

**Comment by MilesCranmer** [comment]
I guess this might cause other issues in case someone wants to view the csv file... So maybe I need to stop using unicode characters for CSV (and only use them for printing).

**Comment by Imageman** [comment]
Yes, working. Thanks.
![изображение](https://github.com/MilesCranmer/PySR/assets/2051167/b341b16c-bd02-4eef-abbb-2ce5fbadd99d)

_"So maybe I need to stop using unicode characters for CSV"_ 
This is a half-hearted solution, as problems with incorrect coding can occur elsewhere. Perhaps we should switch to the usual for programmers writing x[0], x[1], x[2].
