### ISSUE TITLE
[Feature]: How can I use GPU to accelerate training, like deep learning?

### ISSUE THREAD

**Issue by guoaiBB** [MilesCranmer/PySR#454]
### Feature Request

How can I use GPU to accelerate training, like deep learning? and can partial derivative correlation regression be used for data related to partial differential equations?How can I use GPU to accelerate training, like deep learning? and can partial derivative correlation regression be used for data related to partial differential equations?

**Comment by MilesCranmer** [comment]
Hi @guoaiBB,

The backend would have to some changes before it would support CUDA natively.

I think basically it would need to be able to store symbolic expressions as some CUDA arrays in a new `Node{T}`-like type that subtypes `AbstractNode`: https://github.com/SymbolicML/DynamicExpressions.jl/blob/master/src/Equation.jl. It might be a lot of work FYI.

But, if you're just using CUDA for array evaluation, then it shouldn't be so bad. It might already work (on the Julia side of things). Take a look at https://github.com/JuliaGPU/CUDA.jl.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Closing in favor of https://github.com/SymbolicML/DynamicExpressions.jl/issues/31

**Comment by guoaiBB** [comment]
Thank you very much.I have some questions at the moment.
 I am recently using pysr to perform regression on data where the input x,
y, z output is temperature.
However, the data volume is relatively large, with 300k rows of data, and
the fitting effect is not very good. Could you please give me some advice?
In addition, I would like to ask whether pysr can perform regression on
partial differential operators, such as data simulated by cfd that solves
ns equations.
Thank you very much again

Miles Cranmer ***@***.***> 于2023年11月12日周日 22:32写道：

**Comment by MilesCranmer** [comment]
Hi @guoaiBB,

If it's okay with you, could you post your questions separately? Generally I try to keep one topic per issue/discussion so it's easier for people to find if they search it.

For this question in particular, it's good if you could initially check the tuning advice page (https://astroautomata.com/PySR/tuning/) as well as the forums (https://github.com/MilesCranmer/PySR/discussions). If you can't find an answer there then feel free to post a new discussion for help.

(300k rows is too large for PySR; you generally only need 5k max)

Cheers,
Miles

**Comment by guoaiBB** [comment]
Thanks for the tip!

Miles Cranmer ***@***.***> 于2023年11月12日周日 23:34写道：
