### ISSUE TITLE
[BUG]: Small typo in documentation

### ISSUE THREAD

**Issue by manuel-morales-a** [MilesCranmer/PySR#489]
### What happened?

There is a trivial bug in the README.md, a typo. 

When defining a `PySRRegressor`, at some point it says `denoising=True` when the correct syntax is simply  `denoise=True`. 

### Version

0.16.5

### Operating System

macOS

### Package Manager

None

### Interface

Jupyter Notebook

### Relevant log output

```shell
n/a.
```

### Extra Info

It seems that I can't push a local branch that fixes the typo to the remote, otherwise I would've made a PR (and PR-ing a fork for this issue seems like an overkill). 

Thanks!

**Comment by MilesCranmer** [comment]
Thanks! Just fixed it.
