### ISSUE TITLE
[Question] Empty list for unary_operators

### ISSUE THREAD

**Issue by sheevy** [MilesCranmer/PySR#5]
Hey,

Is there a technical reason why `unary_operators` argument cannot be an empty list? When I tried that it failed with:
```
assert len(unary_operators) > 0
```

**Comment by MilesCranmer** [comment]
From an algorithmic perspective, it's fine to have no unary operators. I simply have not written/tested the code yet to allow for it. The assert is to prevent errors/undefined behavior from the Julia side. 

At the minimum, I always use "neg" (=negative; though this is redundant as mult(-1.0, ...) is equivalent) so I didn't see the need to add code for empty unary operators. But I can add it if you'd like.

**Comment by MilesCranmer** [comment]
Just let me know if you'd like that added. Closing for now.

**Comment by MilesCranmer** [comment]
Okay so it turns out I wrote the code in such a way that everything is already functional without unary operators! Sorry for that assert statement. I have removed it.

**Comment by MilesCranmer** [comment]
An empty list for binary_operators works as well, it turns out!
