### ISSUE TITLE
Update Head Worker Occupation Warning

### ISSUE THREAD

**Issue by kmlefran** [MilesCranmer/PySR#551]
Just a minor thing I noticed in my output that might want to be updated.

With the renaming of `ncyclesperiteration` to `ncycles_per_iteration`, the error message for high head worker occupation should probably be updated, as it still references `ncyclesperiteration`. Here is the warning I got in my run (with `ncycles_per_iteration` provided to `PySRRegressor`)

"Head worker occupation: 22.1%. This is high, and will prevent efficient resource usage. Increase `ncyclesperiteration` to reduce load on head worker."

**Comment by MilesCranmer** [comment]
Good catch! Thanks. (Happy to take a PR; will get to this hopefully soon otherwise)

**Comment by MilesCranmer** [comment]
Okay I fixed it with https://github.com/MilesCranmer/SymbolicRegression.jl/commit/e028cb1d5c60816972aee76270ed60a78b300a2c. Just need to have the new backend version propagate.

**Comment by MilesCranmer** [comment]
Fixed in #564.
