### ISSUE TITLE
Command '['julia', '-e', '...']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by LeoVoltolini** [MilesCranmer/PySR#555]
### What happened?

[BUG]: I installed the Juliaup direct from Windows terminal (MS store) and also I already had a Python version from MS Store. I'm using VS Code and when I was trying to run the code example, I'm getting the following error message: subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1. Do you have any idea what this is could be?

### Version

0.16.9

### Operating System

Windows

### Package Manager

pip

### Interface

Script (i.e., `python my_script.py`)

**Comment by MilesCranmer** [comment]
Can you install the new version of PySR and try again?

**Comment by MilesCranmer** [comment]
Going to close this as it is fixed in the most recent version. Let me know if it comes up again though...
