### ISSUE TITLE
[Feature]: TensorBoard support

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/PySR#581]
### Feature Request

Just to track https://github.com/MilesCranmer/SymbolicRegression.jl/pull/277 on the PySR side. We can have another install on the Julia side in `pysr/julia_extensions.py` for TensorBoard and Wandb.

**Comment by BrotherHa** [comment]
Hello @MilesCranmer, 
I am working with PySR for my master´s thesis and noticed the new option of SymbolicRegression.jl to specify a logger. I am interested in this feature and therefore I wanted to ask, if it is already possible to use the logging option with PySR and if that is the case, how to implement it? I already tried to "update" the SymbolicRegression.jl File used in PySR manually to use the latest SymbolicRegression.jl version, like explained here (https://astroautomata.com/PySR/backend/), which did unfortunately not work.
Thank you very much for your support in advance!
Best Regards

**Comment by MilesCranmer** [comment]
See https://github.com/MilesCranmer/PySR/pull/748. The 1.0 change requires a lot of updates. But it still doesn’t have the tensorboard logger built in, that’s still a todo item.

**Comment by MilesCranmer** [comment]
Ok I added tensorboard logging in #748. Will merge soon...

**Comment by MilesCranmer** [comment]
Released
