### ISSUE TITLE
Unable to run 2nd last cell

### ISSUE THREAD

**Issue by 29shubham95** [MilesCranmer/PySR#626]
<img width="482" alt="issue" src="https://github.com/MilesCranmer/PySR/assets/58954022/7d02af4f-866f-41ad-b318-7bf8fb404196">

I was trying to run this segment at the end. It first gave me a warning "It seems you are running in jupyter......". Then I skipped the warning and resumed it after which it gave me the error shown in the given figure. Can you please help me to solve this issue.

Thanks in advance
Shubham

**Comment by MilesCranmer** [comment]
`g_input` needs to be transposed
