### ISSUE TITLE
issue with calling best_callable when best returns a constant function.

### ISSUE THREAD

**Issue by bowenyou** [MilesCranmer/PySR#64]
When calling best_callable on a function pysr returns as a constant, I get the following error.

TypeError: _lambdifygenerated() missing 1 required positional argument: 'x1'

Could best_callable be adapted for constant functions as well?

**Comment by MilesCranmer** [comment]
What version of PySR are you running? This looks like the old API.

**Comment by bowenyou** [comment]
I have this version pysr-0.5.16.post2 and even uninstalling and reinstalling gives me this version using pip. Is there a julia/python version requirement?

**Comment by MilesCranmer** [comment]
Ah, that is why. You need 0.6 and up. Upgrade with:
```
pip install --upgrade pysr
```

**Comment by MilesCranmer** [comment]
By the way - sorry I didn't mention it, but to use `best_callable`, pass the same `X` as you passed to the PySR call. The same is true even for constant solutions (though in that case, I suppose any array would work...).
