### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jzsmoreno** [MilesCranmer/PySR#67]
I have installed pysr-0.6.12.post1 and I have been try to run the example.py but after solve some previous closed bug reports a FileNotFoundError occurs. I'm using Windows 10 and Python 3.7 the version of Julia is 1.6.2. The error message is the following.

FileNotFoundError: [Errno 2] No such file or directory: 'hall_of_fame_2021-08-04_230410.180.csv.bkup'

**Comment by MilesCranmer** [comment]
Sorry for the late response.

This error message occurs when PySR can't find the output of the symbolic regression search. It could occur for many different reasons, though. What is the full message that was printed? I think that will give me a clue for what is going on.

Cheers,
Miles

**Comment by jzsmoreno** [comment]
Sorry too for the late.

The message after the one I show above is the following below. I don't know if you need the full message. The section where it raise the RuntimeError is this, `equations = get_hof(**kwargs)`. I hope that this could help. Thanks alot 

RuntimeError: Couldn't find equation file! The equation search likely exited before a single iteration completed. 

Cheers,
José

**Comment by MilesCranmer** [comment]
No worries.
Can you send the full error message? This error is similar to the first error - it is a result of the backend not correctly executing the search.

**Comment by jzsmoreno** [comment]
The full message is the following: 

```
in expression starting at C:\Users\Valeria\AppData\Local\Temp\tmpy85xyhl6\runfile.jl:7
Traceback (most recent call last):
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pysr\sr.py", line 1001, in get_hof
    all_outputs = [pd.read_csv(str(equation_file) + ".bkup", sep="|")]
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'hall_of_fame_2021-08-12_144743.312.csv.bkup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "untitled0.py", line 16, in <module>
    equations = pysr(
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pysr\sr.py", line 478, in pysr
    equations = get_hof(**kwargs)
  File "C:\Users\Valeria\anaconda3\lib\site-packages\pysr\sr.py", line 1003, in get_hof
    raise RuntimeError(
RuntimeError: Couldn't find equation file! The equation search likely exited before a single iteration completed.
```

**Comment by MilesCranmer** [comment]
Weird, are there no other logs (output of Julia)? The Julia error message is what I usually look for.

**Comment by jzsmoreno** [comment]
Sorry for the late, here it is:
```
Running on julia -O3 C:\Users\Valeria\AppData\Local\Temp\tmpdmv52hz8\runfile.jl
  Activating environment at `C:\Users\Valeria\anaconda3\lib\site-packages\Project.toml`
    Updating registry at `C:\Users\Valeria\.julia\registries\General`
  No Changes to `C:\Users\Valeria\anaconda3\Lib\site-packages\Project.toml`
  No Changes to `C:\Users\Valeria\anaconda3\Lib\site-packages\Manifest.toml`
ERROR: LoadError: InexactError: trunc(Int32, 2.8980162473e10)
```

**Comment by MilesCranmer** [comment]
Hi @jzsmoreno,

I think I finally figured this out, it took me a while. I think this issue is caused by the issue described at the bottom of this thread: (in the backend code) https://github.com/MilesCranmer/SymbolicRegression.jl/issues/43, which I just fixed in both PySR and the backend. Can you try out the new version of PySR (0.6.13), and tell me if this  happens again?

Thanks!
Miles

**Comment by jzsmoreno** [comment]
Hi @MilesCranmer,

I update the package as you mention, but now I get a similar error `FileNotFoundError: [Errno 2] No such file or directory: 'hall_of_fame_2021-09-14_225224.625.csv.bkup'` and the output of Julia is the following.

```
Running on julia -O3 C:\Users\Valeria\AppData\Local\Temp\tmpovz0l_ns\runfile.jl
  Activating environment at C:\Users\Valeria\anaconda3\lib\site-packages\Project.toml
    Updating registry at C:\Users\Valeria\.julia\registries\General
    Updating git-repo https://github.com/JuliaRegistries/General.git
  No Changes to C:\Users\Valeria\anaconda3\Lib\site-packages\Project.toml
  No Changes to C:\Users\Valeria\anaconda3\Lib\site-packages\Manifest.toml
ERROR: LoadError: InexactError: trunc(Int32, 3.1678560497e10)
```

Thanks! By the way... sorry for the trouble
José

**Comment by MilesCranmer** [comment]
Hi @jzsmoreno,
Does this issue still occur when you set `multithreading=True`?
Cheers,
Miles

**Comment by jzsmoreno** [comment]
Hi @MilesCranmer ,

Sorry for the inconvenience. It's wierd, when I don't use `multithreading=True`, I also obtain the following output:

`FileNotFoundError: [Errno 2] No such file or directory: 'hall_of_fame_2022-01-10_130751.568.csv.bkup'`

But when I use `multithreading=True`, all I get is the following:

`ERROR: LoadError: InexactError: trunc(Int32, 4.1844363392e10)`

Cheers, hope you're well 
José

**Comment by MilesCranmer** [comment]
Hm, I'm really not sure what this is from. Can you send me your full script and data file (if applicable)?

Thanks,
Miles

**Comment by jzsmoreno** [comment]
I'm really start to think that is an error of Julia, because I couldn't simply run the example.py file. The errors I get are the ones from running the example. This is the entire output: 

`Running on julia -O3 --threads 4 C:\Users\jzsmo\AppData\Local\Temp\tmpdkf7vvk_\runfile.jl`
  **Activating environment at** `C:\Users\jzsmo\SymbolicRegression.jl\Project.toml`
    **Updating registry at** `C:\Users\jzsmo\.julia\registries\General`
    **Updating git-repo** `https://github.com/JuliaRegistries/General.git`
  **No Changes to** `C:\Users\jzsmo\SymbolicRegression.jl\Project.toml`
  **No Changes to** `C:\Users\jzsmo\SymbolicRegression.jl\Manifest.toml`
`ERROR: LoadError: InexactError: trunc(Int32, 4.1844552344e10)`
`Stacktrace:`
 

> ` [1] trunc`
>     `@ .\float.jl:695 [inlined]`
>   `[2] round`
>     `@ .\float.jl:296 [inlined]`
>   `[3] getTime`
>     `@ C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\Utils.jl:19 [inlined]`
>   `[4] PopMember(t::Node, score::Float32; ref::Int32, parent::Int32)`
>     `@ SymbolicRegression...\PopMember.jl C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\PopMember.jl:31`
>   `[5] #PopMember#2`
>     `@ C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\PopMember.jl:51 [inlined]`
>   `[6] PopMember`
>     `@ C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\PopMember.jl:51 [inlined]`
>   `[7] (::SymbolicRegression...\Population.jl.var"#2#3"{Int32, Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, Int32, SymbolicRegression...\Dataset.jl.Dataset{Float32}, Float32})(i::Int32)`
>     `@ SymbolicRegression...\Population.jl .\none:0`
>  ` [8] iterate`
>     `@ .\generator.jl:47 [inlined]`
>   `[9] collect`
>     `@ .\array.jl:678 [inlined]`
>  `[10] #Population#1`
>     `@ C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\Population.jl:29 [inlined]`
> ` [11] (::SymbolicRegression.var"#37#69"{Int32, Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, Vector{SymbolicRegression...\Dataset.jl.Dataset{Float32}}})(i::Int32)`
>     `@ SymbolicRegression .\none:0`
> ` [12] iterate`
>     `@ .\generator.jl:47 [inlined]`
>  `[13] collect(itr::Base.Generator{UnitRange{Int32}, SymbolicRegression.var"#37#69"{Int32, Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, Vector{SymbolicRegression...\Dataset.jl.Dataset{Float32}}}})`
>     `@ Base .\array.jl:678`
>  `[14] #36`
>     `@ .\none:0 [inlined]`
>  `[15] iterate`
>     `@ .\generator.jl:47 [inlined]`
>  `[16] collect(itr::Base.Generator{UnitRange{Int32}, SymbolicRegression.var"#36#68"{Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, Vector{SymbolicRegression...\Dataset.jl.Dataset{Float32}}}})`
>     `@ Base .\array.jl:678`
>  `[17] _EquationSearch(::SymbolicRegression...\ProgramConstants.jl.SRThreaded, datasets::Vector{SymbolicRegression...\Dataset.jl.Dataset{Float32}}; niterations::Int32, options::Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, numprocs::Int32, procs::Nothing, runtests::Bool)`
>     `@ SymbolicRegression C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\SymbolicRegression.jl:241`
>  `[18] EquationSearch(datasets::Vector{SymbolicRegression...\Dataset.jl.Dataset{Float32}}; niterations::Int32, options::Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, numprocs::Int32, procs::Nothing, multithreading::Bool, runtests::Bool)`
>    ` @ SymbolicRegression C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\SymbolicRegression.jl:181`
>  `[19] EquationSearch(X::Matrix{Float32}, y::Matrix{Float32}; niterations::Int32, weights::Nothing, varMap::Vector{String}, options::Options{Tuple{typeof(+), typeof(*)}, Tuple{typeof(cos), typeof(exp), typeof(sin), typeof(inv)}, typeof(loss)}, numprocs::Int32, procs::Nothing, multithreading::Bool, runtests::Bool)`
>     `@ SymbolicRegression C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\SymbolicRegression.jl:145`
>  `[20] #EquationSearch#22`
>     `@ C:\Users\jzsmo\.julia\packages\SymbolicRegression\dhfuI\src\SymbolicRegression.jl:157 [inlined]`
> ` [21] top-level scope`
>    ` @ C:\Users\jzsmo\AppData\Local\Temp\tmpdkf7vvk_\runfile.jl:7`
> `in expression starting at C:\Users\jzsmo\AppData\Local\Temp\tmpdkf7vvk_\runfile.jl:7`
> `Traceback (most recent call last):`
>  ` File "C:\Users\jzsmo\anaconda3\lib\site-packages\pysr\sr.py", line 1005, in get_hof`
>     `all_outputs = [pd.read_csv(str(equation_file) + ".bkup", sep="|")]`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper`
>     `return func(*args, **kwargs)`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv`
>     `return _read(filepath_or_buffer, kwds)`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read`
>     `parser = TextFileReader(filepath_or_buffer, **kwds)`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__`
>     `self._engine = self._make_engine(self.engine)`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine`
>     `return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__`
>     `self._open_handles(src, kwds)`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py", line 229, in _open_handles`
>     `errors=kwds.get("encoding_errors", "strict"),`
>   `File "C:\Users\jzsmo\anaconda3\lib\site-packages\pandas\io\common.py", line 707, in get_handle`
>     `newline="",`
> 

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
 ```
 File "c:\Users\jzsmo\Documents\example.py", line 22, in <module>
    multithreading=True,
  File "C:\Users\jzsmo\anaconda3\lib\site-packages\pysr\sr.py", line 482, in pysr
    equations = get_hof(**kwargs)
  File "C:\Users\jzsmo\anaconda3\lib\site-packages\pysr\sr.py", line 1008, in get_hof
    "Couldn't find equation file! The equation search likely exited before a single iteration completed."
RuntimeError: Couldn't find equation file! The equation search likely exited before a single iteration completed.
```

Thanks to you,  
José

**Comment by MilesCranmer** [comment]
What version of Julia is this? Have you tried a newer Julia version? This is very strange indeed... sorry I haven't figured this out yet. All the unit tests pass on Windows so I'm not sure if it's a Windows Julia issue or what.

Can you set `delete_tempfiles=False`, and then locate the directory containing `runfile.jl` (it prints where this file is stored)? These are all the Julia files it is using to run the search. Can you give me the contents of `runfile.jl`?

Cheers,
Miles

**Comment by jzsmoreno** [comment]
Don't worry, it happens, this is the file `runfile.jl` and it is located here `C:\Users\jzsmo\AppData\Local\Temp\tmpoz6wg5a8`. The version of Julia is 1.6.2
```
import Pkg
Pkg.activate("..\\SymbolicRegression.jl")
Pkg.update()
using SymbolicRegression
include("C:\\Users\\jzsmo\\AppData\\Local\\Temp\\tmpoz6wg5a8\\hyperparams.jl")
include("C:\\Users\\jzsmo\\AppData\\Local\\Temp\\tmpoz6wg5a8\\dataset.jl")
EquationSearch(X, y, niterations=5, varMap=["x0","x1","x2","x3","x4"], options=options, numprocs=0, multithreading=true)
```

Sorry again for the inconvenience,
José

**Comment by jzsmoreno** [comment]
Sorry for the late @MilesCranmer, already tried it but I get the same result with this `runfile.jl` output.

```
import Pkg
Pkg.activate("C:\\Users\\jzsmo\\anaconda3\\lib\\site-packages")
Pkg.update()
using SymbolicRegression
include("C:\\Users\\jzsmo\\AppData\\Local\\Temp\\tmpjp94ffd1\\hyperparams.jl")
include("C:\\Users\\jzsmo\\AppData\\Local\\Temp\\tmpjp94ffd1\\dataset.jl")
EquationSearch(X, y, niterations=5, varMap=["x0","x1","x2","x3","x4"], options=options, numprocs=0, multithreading=true)
```

Thanks, 
José

**Comment by MilesCranmer** [comment]
Thanks!

So, I finally figured this out. I think your version of SymbolicRegression.jl is very out-of-date. The bug you are seeing is from this function `getTime`, as of the version one year ago:
```julia
function getTime()::Int
    return round(Int32, 1e3*(time()-1.6e9))
end
```
This only has 32-bit precision, hence issues with rounding with computing the current time. In fact I can reproduce your bug like so:
```julia
julia> round(Int32, 1e3*(time()-1.6e9))
ERROR: InexactError: trunc(Int32, 4.1974427244e10)
Stacktrace:
 [1] trunc
   @ ./float.jl:695 [inlined]
 [2] round(#unused#::Type{Int32}, x::Float64)
   @ Base ./float.jl:296
 [3] top-level scope
   @ REPL[1]:1
```

This was patched 1 year ago, in version 0.3.0 of SymbolicRegression.jl (and version PySR 0.3.0). All versions after this have instead:
```julia
function getTime()::Int
    return round(Int, 1e3*(time()-1.6e9))
end
```
which is 64-bit precision.

So the next question is: why does your machine choose a version of SymbolicRegression.jl that is <0.3.0, when the current version requires version 0.6.10? I am confused about this.

Can you print the contents of `C:\Users\jzsmo\SymbolicRegression.jl\Project.toml`?

Thanks,
Miles

**Comment by jzsmoreno** [comment]
Thank you very much @MilesCranmer is that the problem! I ran the following command `Pkg.add(PackageSpec(name="SymbolicRegression", version="0.6.10"))`  on Julia but I obtain the following error:

`ERROR: UndefVarError: PackageSpec not defined`

The contents of  `C:\Users\jzsmo\SymbolicRegression.jl\Project.toml` is empty

**Comment by jzsmoreno** [comment]
Sorry @MilesCranmer for all the problems, indeed that was the problem, using a 32-bit version of Julia. With the 64-bit version I had no problem and it is already running the example. I think this is the root of many other issues. Like the other one I commented on. With this I think we can close the issue.

Thanks, 
José

**Comment by MilesCranmer** [comment]
Amazing!!! I am very happy we could solve this. Sorry it took so long, but glad it finally is working!
Cheers,
Miles

**Comment by jzsmoreno** [comment]
Hi @MilesCranmer 

Yes! After some time, but we finally did it... But the way!, I have a python package called likelihood, if you wanna help me to improve it. 

Cheers,
José
