### ISSUE TITLE
[BUG]: Hard crash on import from MacOS System Integrity Protection (SIP)

### ISSUE THREAD

**Issue by ev-watson** [MilesCranmer/PySR#682]
### What happened?

upon pip installing pysr into a virtual environment, making sure my PATH variable has the bin, exporting LD_LIBRARY_PATH as specified in github readme, and even removing quarantine status for the environment, importing pysr still results in python quitting

julia version supports arch64 (silicon)

### Version

Any version of PySR

### Operating System

macOS

### Package Manager

pip

### Interface

Jupyter Notebook

### Relevant log output

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [40891]
Path:                  /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            com.apple.python3
Version:               3.9.6 (3.9.6)
Build Info:            python3-141000000000000~1415
Code Type:             ARM-64 (Native)
Parent Process:        python [40765]
Responsible:           pycharm [40727]
User ID:               501

Date/Time:             2024-07-27 21:46:46.1280 -0700
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        6F31D97B-2A3B-8D95-FA9E-B1FE5CB86DF1

Sleep/Wake UUID:       404515B4-A7B3-4531-A2F4-F7C17B16EC40

Time Awake Since Boot: 240000 seconds
Time Since Wake:       27250 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_GUARD (SIGKILL)
Exception Codes:       GUARD_TYPE_MACH_PORT
Exception Codes:       0x0000000000012740, 0x0000000000000000

Termination Reason:    Namespace GUARD, Code 2305843035917854528
```

### Extra Info

tried all sorts of PySR and Julia versions, this seems to be independent of that, id prefer a solution that doesnt involve me booting in RecoveryOS and disabling SIP, although this is what I have done in the meantime

**Comment by ev-watson** [comment]
just to be clear, booting into RecoveryOS and disabling the security protocol DOES solve this issue, so surely there is a fix that can be made, maybe permissions can be set somewhere or something

**Comment by MilesCranmer** [comment]
1. Can you launch Julia by itself?
2. Then, can you import `juliacall` by itself, or does that trigger the error too?
3. Do you have any corporate security tools that might be causing this? Note that PySR attempts to install Julia the first time you import it. 

If (1) is okay, but (2) is not, perhaps you could try forcing the version of Julia it is loading? You can do this with the environment variables here: https://juliapy.github.io/PythonCall.jl/stable/juliacall/#julia-config

**Comment by ev-watson** [comment]
I can launch julia just fine, i can also import juliacall by itself, once I did this, i then imported pysr and everything worked just fine
If i restart my jupyter server and import pysr alone it crashes, but if i import juliacall before pysr everything works and i can regress an equation. For clarity this works:
```
import juliacall
import pysr
```
-----------------------
But this causes the security protocol to be triggered:
```
import pysr
```
i do not have any corporate security tools, this was just Apple's own disk System Integrity Protection force killing python. So obviously it is because pysr cant install julia, or at least right now it just does so in way that triggers SIP,

Thanks for the help,

**Comment by MilesCranmer** [comment]
> but if i import juliacall before pysr everything works and i can regress an equation

Interesting. So the only things that this could change are the environment variables set within `pysr/julia_import.py`. I wonder if you set those manually, if any environment variable in particular triggers the error? Perhaps the multithreaded setting is causing it?

e.g., https://github.com/MilesCranmer/PySR/blob/3aee19e38ceb3e0e1617d357a831400e01204658/pysr/julia_import.py#L24

Basically if you import juliacall beforehand, these environment variables in this file will not be used. So maybe one of the variables is causing the issue.

**Comment by ev-watson** [comment]
Setting manually does not trigger an error, I ran the code provided above without importing pysr and it ran, but then upon importing PySR, even with the environment variables set, it still triggered security protocol

**Comment by MilesCranmer** [comment]
Can you set the environment variables, and then import juliacall? (i.e., no PySR)

**Comment by MilesCranmer** [comment]
Thanks, that is super useful! So it sounds like that one environment variable is the issue here. (You can ignore the other two, they seem to not affect it).

Would it be possible for you to make an issue on PythonCall.jl (same thing as juliacall)? Here: https://github.com/JuliaPy/PythonCall.jl/issues

It sounds like an issue is unrelated to PySR so we can solve it over there instead. I would just copy the minimal example you mentioned to an issue there (without the other two env variables), and explain how it is triggering system integrity protection issues.

**Comment by ev-watson** [comment]
Done, thanks for all the help
