### ISSUE TITLE
PySR could not start julia. Make sure julia is installed and on your $PATH.

### ISSUE THREAD

**Issue by Ting-TingGao** [MilesCranmer/PySR#70]
Hello Miles! Ⅰ am trying to apply your PySR to some biological dataset and wish to find some interesting results (something like compact ODE/SDE). But Ⅰ am kind of new to Julia, and when Ⅰ try to run the example, this bug jumps: "PySR could not start Julia. Make sure Julia is installed and on your $PATH". Ⅰ looked for some solution (add Julia path to the current workspace?) but Ⅰ still can't solve this problem, would you mind giving a solution? Thanks in advance.

**Ⅰ am trying to run on Mac, and the Julia version is 1.6 ('/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia'). **

And also Ⅰ am curious that if PySR will be robust when data is noisy.  

Thank you very much!

**Comment by MilesCranmer** [comment]
As a quick fix you can add this to the top of your script:
```
import os
os.environ["PATH"] += ":/Applications/Julia-1.6.app/Contents/Resources/julia/bin"
```

**Comment by Ting-TingGao** [comment]
Thank you for replying so quickly! 
It works!  :)

**Comment by MilesCranmer** [comment]
No problem!
