### ISSUE TITLE
[BUG] Worker not responding after 1 min

### ISSUE THREAD

**Issue by Magaud59** [MilesCranmer/PySR#72]
Dear PySR Experts,

I've been using PySR since few weeks now and I'm very happy of it's capabilities.

For a reason I ignore, it's crashing since 2 days.

It's seems to be link to none responding workers after waiting 1 min.

I tried to use the base example script from PySR but it's generating the same error.

**Version (please complete the following information):**
- OS: Linux Mint 19.3
- 0.6.12.post1
- Does the bug appear with the latest version of PySR? I don't know...

**Configuration**
- What are your PySR settings? No specific settings
- What dataset are you running on?  base example script from PySR

**Error message**
attached

**Additional context**
possible conda-forge update... but reinstalled entirely anaconda, julia and pysr following that without any change... only once, the base example went through properly, started from standard terminal (out of anaconda + spyder)
[Output_Error.txt](https://github.com/MilesCranmer/PySR/files/7021344/Output_Error.txt)

**Comment by Magaud59** [comment]
Following the reading of "ERROR: The following package names could not be resolved/Julia servers out of date",
I'm trying to update julia's package as explained. 
I'll keep you inform after test

**Comment by Magaud59** [comment]
I ran the base example again and still obtain a crash.
The message is different from before, much longer... and in the middle, my prompt is appearing... weird...
Anyway, the output error file is attached. Hopefuly, it will help.
thanks for your support!

[Output_Error_2.txt](https://github.com/MilesCranmer/PySR/files/7021420/Output_Error_2.txt)

**Comment by MilesCranmer** [comment]
Can you try with `multithreading=True` as an argument to PySR? That will run in threaded mode instead of multiprocessing mode, it might help.

**Comment by Magaud59** [comment]
Hi Miles,

thanks for taking care of my case.

You are right. The exemple as well as my implementation went both fine till the end. That very nice.

What is the main problem there? is it the distrib I'm using (Mint) or simply my hardware?

**Comment by MilesCranmer** [comment]
I am not sure. @kazewong mentioned he has seen something similar with the workers in the latest version. I will look into this when I have more bandwidth.

Cheers,
Miles
