### ISSUE TITLE
[BUG]: `cluster_manager="slurm"` is not working

### ISSUE THREAD

**Issue by dhjx1996** [MilesCranmer/PySR#769]
### What happened?

I am attempting to run PySR on multiple nodes of a slurm cluster. I have attempted not passing a `cluster_manager` argument at all but then all but one node will remain idle. When I pass `cluster_manager="slurm"` into PySRRegressor, I get the following error:

> juliacall.JuliaError: ArgumentError: Package ClusterManagers not found in current path.
> \- Run `import Pkg; Pkg.add("ClusterManagers")` to install the ClusterManagers package.

### Version

0.19.4

### Operating System

Windows, Linux

### Package Manager

pip

### Interface

Script (i.e., `python my_script.py`)

### Relevant log output

```shell
> Traceback (most recent call last):
> File "/burg/home/dh3065/twostream_PySR_RTsources_Dec06_small5_multinode/twostream_PySR_RTsources.py", line 127, in
> modelRpT.fit(X_sample, y1_sample)
> File "/burg/home/dh3065/miniconda3/envs/2stream/lib/python3.12/site-packages/pysr/sr.py", line 2087, in fit
> self._run(X, y, runtime_params, weights=weights, seed=seed)
> File "/burg/home/dh3065/miniconda3/envs/2stream/lib/python3.12/site-packages/pysr/sr.py", line 1694, in _run
> cluster_manager = _load_cluster_manager(cluster_manager)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/burg/home/dh3065/miniconda3/envs/2stream/lib/python3.12/site-packages/pysr/julia_helpers.py", line 31, in load_cluster_manager
> jl.seval(f"using ClusterManagers: addprocs{cluster_manager}")
> File "/burg/home/dh3065/.julia/packages/PythonCall/Nr75f/src/JlWrap/module.jl", line 27, in seval
> return self._jl_callmethod($(pyjl_methodnum(pyjlmodule_seval)), expr)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> juliacall.JuliaError: ArgumentError: Package ClusterManagers not found in current path.
> 
> Run import Pkg; Pkg.add("ClusterManagers") to install the ClusterManagers package.
> Stacktrace:
> [1] macro expansion
> @ ./loading.jl:1772 [inlined]
> [2] macro expansion
> @ ./lock.jl:267 [inlined]
> [3] _require(into::Module, mod::Symbol)
> @ Base ./loading.jl:1753
> [4] #invoke_in_world#3
> @ ./essentials.jl:926 [inlined]
> [5] invoke_in_world
> @ ./essentials.jl:923 [inlined]
> [6] require(into::Module, mod::Symbol)
> @ Base ./loading.jl:1746
> [7] eval
> @ ./boot.jl:385 [inlined]
> [8] eval
> @ ./Base.jl:88 [inlined]
> [9] pyjlmodule_seval(self::Module, expr::Py)
> @ PythonCall.JlWrap ~/.julia/packages/PythonCall/Nr75f/src/JlWrap/module.jl:13
> [10] pyjl_callmethod(f::Any, self::Ptr{PythonCall.C.PyObject}, args::Ptr{PythonCall.C.PyObject}, nargs::Int64)
> @ PythonCall.JlWrap ~/.julia/packages/PythonCall/Nr75f/src/JlWrap/base.jl:67
> [11] _pyjl_callmethod(o::Ptr{PythonCall.C.PyObject}, args::Ptr{PythonCall.C.PyObject})
> @ PythonCall.JlWrap.Cjl ~/.julia/packages/PythonCall/Nr75f/src/JlWrap/C.jl:63
```

### Extra Info

This produces the error:

```
modelRpT = PySRRegressor(
    procs=56, # Trying 2 nodes with 28 cores each
    cluster_manager="slurm",
    populations=56*3,
    multithreading=False,
    binary_operators=["+", "-", "*", "/"], # Default
    unary_operators=["exp"],
    #niterations=100,
    nested_constraints={"exp": {"exp": 0}},
    maxsize=45,
    #warmup_maxsize_by=0.5,
    bumper=True,
    warm_start=True,
    verbosity=0,
    #weight_optimize=0.001,
    #adaptive_parsimony_scaling=1000,
    parsimony=0.01**2 / 10,
)

modelRpT.fit(X_sample, y1_sample)
```

**Comment by MilesCranmer** [comment]
@dhjx1996 could you please upgrade PySR to at least version 1? The line here: https://github.com/MilesCranmer/PySR/blob/3433e5d92ebea731e9c4a4361cc8981fc0953291/pysr/julia_extensions.py#L24-L25 should solve this.

**Comment by dhjx1996** [comment]
> @dhjx1996 could you please upgrade PySR to at least version 1? The line here:
> 
> https://github.com/MilesCranmer/PySR/blob/3433e5d92ebea731e9c4a4361cc8981fc0953291/pysr/julia_extensions.py#L24-L25
> 
> should solve this.

Hi @MilesCranmer yup, I got it working now! Thank you very much for your help.

It seems like `Bumper.jl`, `ClusterManagers.jl` and `SymbolicRegression.jl` are not automatically installed after the upgrade, which also upgraded Julia, and I had to manually install them before PySR worked again. I am not sure if that is intended behavior.

Finally, a completely separate question if you don't mind: you recommended using `bumper` for speedup and I have activated it. Would you also recommend activating `turbo`, i.e. `LoopVectorization.jl`? Thank you once again!

**Comment by MilesCranmer** [comment]
Cool!

> It seems like `Bumper.jl`, `ClusterManagers.jl` and `SymbolicRegression.jl` are not automatically installed after the upgrade, which also upgraded Julia, and I had to manually install them before PySR worked again. I am not sure if that is intended behavior.

Hm. That’s not intended. They should be automatically installed though. Maybe it’s just a one-time issue from upgrading, and if you set up a new environment, it would work?

> Finally, a completely separate question if you don't mind: you recommended using `bumper` for speedup and I have activated it. Would you also recommend activating `turbo`, i.e. `LoopVectorization.jl`? Thank you once again!

Yes the `turbo=True` (LoopVectorization.jl) is far more effective for speed than `bumper=True` (Bumper.jl). The bumper one is more subtle and has to do with Julia’s garbage collection. You can also try both. It’s problem dependent so it’s worth trying each option.
