### ISSUE TITLE
[Feature]: Some compatibility issues in version 1.1

### ISSUE THREAD

**Issue by jackeuylov** [MilesCranmer/PySR#771]
### Feature Request

Hi Miles @MilesCranmer
Thanks for developing the helpful tool! 
In my model, the equation expression to be sought is relatively complex - the complexity is usually between 20-30, and I have around 10 independent variables, with a large amount of data. In this case, I would like to introduce an initial equation into the expression tree: start evolving from this expression, rather than generating a set of random initial expressions. Is it possible to implement this function in the current pysr framework?
By the way, my PySR version is 0.19.4 because for my reason, I have found that the older model parameters are more beneficial for my problem.

**Comment by MilesCranmer** [comment]
Hi @jackeuylov,

Have you tried the new TemplateExpressionSpec approach? i.e., https://ai.damtp.cam.ac.uk/pysr/examples/#template-expressions. You would write out the initial expression and then learn modifications to it. Especially with a lot of variables this is probably helpful for your problem to make things easier.

**Comment by MilesCranmer** [comment]
> The constraints of the equation form and the dimensional constraints are not compatible, and when both exist at the same time, an error will be reported

Yes, these features are not compatible. The implementation would be quite complex. The assertion is there to make sure both features are not used.

> When using tensorboard, the Model loading function will not be compatible (I am very sure that this error will occur after the TensorBoard function is used.)

Thanks, this looks like a bug. Can you please submit another issue with details about how you generated it?

> When I use the Model loading function to continue running the previous results, it seems to run from the initial hall _ of _ fame, rather than from the previous hall _ of _ fame (This problem seems to exist before version 1.0).

Do you have `warm_start=True`? Otherwise it will get reset

**Comment by jackeuylov** [comment]
> > 方程式的约束和尺寸约束不兼容，当两者同时存在时，将报告错误
> 
> 是的，这些功能不兼容。实现将相当复杂。该断言用于确保这两个功能均未被使用。
> 
> 也许这可能会有一个 Python 错误，以使其更明显地是故意的？
> 
> > 使用 tensorboard 时，Model loading 函数将不兼容（我非常确定使用 TensorBoard 函数后会出现此错误。
> 
> 谢谢，这看起来像一个错误。您能否提交另一个问题，并详细说明您是如何生成的？
> 
> > 当我使用 Model loading 函数继续运行之前的结果时，它似乎是从 _ fame 的初始大厅 _ 运行，而不是从 _ fame 的前一个大厅 _ 运行（这个问题似乎在 1.0 版本之前就存在）。
> 
> 你有吗 ？否则，它将会被重置`warm_start=True`

I have submitted a report on the second question in #779.

**Comment by MilesCranmer** [comment]
Fixed the pkl loading issue in #780!
