### ISSUE TITLE
how to set julia?

### ISSUE THREAD

**Issue by liuzd2017** [MilesCranmer/PySR#86]
I suffer this problem

Your current $PATH is: /home/lzd/miniconda3/envs/hybridmodel/bin:/home/lzd/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PySR could not start julia. Make sure julia is installed and on your $PATH.

could you help me sovle this problem?

**Comment by MilesCranmer** [comment]
What is the output of `which julia`?

**Comment by MilesCranmer** [comment]
Closing as stale; feel free to open again if needed
